/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lumberkodee

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test fun testNameMethod() {
        val classUnderTest = Library()

        val expected = "lumberkodee!"

        assertEquals(expected, classUnderTest.name(), "name should return 'lumberkodee!'")
    }
}
