/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example

import lumberkodee.Library

fun main() {
    val library = Library()

    println("Hello ${library.name()}")
}
