/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example

import com.github.kotlinartisans.lumberkodee.console.ConsoleLumberkodeeClient
import com.github.kotlinartisans.lumberkodee.emoji.EmojiLumberkodeeClient
import com.github.kotlinartisans.lumberkodee.logError
import com.github.kotlinartisans.lumberkodee.logInfo
import com.github.kotlinartisans.lumberkodee.logVerbose
import com.github.kotlinartisans.lumberkodee.logWarning
import com.github.kotlinartisans.lumberkodee.putLumberkodeeToWork

fun main() {
    // Provide lumberkodee clients that will log messages.
    val clients = arrayListOf(ConsoleLumberkodeeClient(), EmojiLumberkodeeClient())

    // Put them to work!
    putLumberkodeeToWork(clients)

    // Start logging from top level API.
    logInfo("My first lumberkodee logging message!")
    logWarning("Attemping to install lumbrekodee from maven...")
    logError(
        "Could not install library...",
        Exception(
            "Package lumbrekodee does not exist! Make sure you download the correct one (@kotlinartisans/lumberkodee)"
        )
    )

    logVerbose("Exiting...");
}
