/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example

import lumberkodee.console.ConsoleLumberkodeeClient
import lumberkodee.emoji.EmojiLumberkodeeClient
import lumberkodee.logError
import lumberkodee.logInfo
import lumberkodee.logVerbose
import lumberkodee.logWarning
import lumberkodee.putLumberkodeeToWork

fun main() {
    // Provide lumberkodee clients that will log messages.
    val clients = arrayListOf(ConsoleLumberkodeeClient(), EmojiLumberkodeeClient())

    // Put them to work!
    putLumberkodeeToWork(clients)

    // Start logging from top level API.
    logInfo("My first lumberkodee logging message!")
    logWarning("Attemping to install lumbrekodee from maven...")
    logError(
        "Could not install library...",
        Exception(
            "Package lumbrekodee does not exist! Make sure you download the correct one (@kotlinartisans/lumberkodee)"
        )
    )

    logVerbose("Exiting...");
}
